### ISSUE TITLE
Otomatik Kanal Numarası Atama ve Ekranda Gösterme 

### ISSUE THREAD

**Issue by ToygarVarli** [barisdinc/ASELSAN_4822#12]
Girilen Kanal Numarasını Frekansa Otomatik Atama ve EEPROM üzerinden kontrol edilebilir şekilde Kanal Numarası ve ya Frekans Görüntüleme Arasında Seçim Yapabilme.

**Comment by barisdinc** [comment]
eline saglik.


bu guzel olmus

**Comment by ToygarVarli** [comment]
Teşekkür ederim hocam :)
