### ISSUE TITLE
ekran ledlerinin kapatilmasi

### ISSUE THREAD

**Issue by barisdinc** [barisdinc/ASELSAN_4822#18]
cihaz belli bir sure kullanilmadiginda ekranin karartilmasi guzel olabilir

**Comment by ToygarVarli** [comment]
Barış Hocam selamlar , 

Uzun zamandır geliştirme yapmıyorduk cihazla ilgili .

Bu issue'ye assign oldum ben. 

SleepTimer yapacağım , tuş takımından gelen interrupt durumuna göre sleeptimer'ı sıfırlayacağım.

Şimdilik 5 saniye olarak sabit yapıyorum. Sonrasında konfigüre edilebilir duruma getiririz.

**Comment by barisdinc** [comment]
Eyvallah... Sagilasin
